==	Интеграции

=== Интеграции с внешними АС-потребителями

Все вызовы фабрики потребителями выполняются по mTLS + OTT с проверкой по ACL.

Фабрика события антфирода обращается в ФП ИС по mTLS с проверкой SAN на стороне ФП ИС.

=== ACL (Access Lists)

Да, все API должны быть закрыты через ACL

1. Api для сохранения и обновления события в агрегаторе антифрод +
Потребители: ППРБ.РКО.ЮЛ.ФП Расчеты Черновики +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> PaymentService -> saveOrUpdateData +
Потребители: ППРБ.РКО.ЮЛ.ФП Расчеты Черновики +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> FastPaymentService -> saveOrUpdateData +
Потребители: ЕФС.ЮЛ.СберБизнес Операции с наличными +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> ElectronicReceiptService -> saveOrUpdateData
Потребители: потребитель, которому необходимо сохранить данные перед отправкой в АС Фрод-монитронг +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> DocumentService -> saveOrUpdateData
2. API для отправки события на анализ в АС Фрод Мониторинг через ФП ИС +
Потребители: ППРБ.РКО.ЮЛ.ФП Расчеты Исполнение ПП +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> PaymentService -> analyzeOperation +
Потребители: ППРБ.РКО.ЮЛ.ФП СБП Расчеты +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> FastPaymentService -> analyzeOperation +
Потребители: ППРБ.Кассовые операции ЮЛ +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> ElectronicReceiptService -> analyzeOperation +
Потребители: ППРБ.Партнеры +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> CounterPartyService -> analyzeOperation +
Потребители: ППРБ.КММБ.Оформление кредита +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> CreditService -> analyzeOperation
Потребители: потребитель, которому необходимо отправить данные в АС Фрод-монитронг после сохранения +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> DocumentService -> analyzeOperation
Потребители: потребитель, которому необходимо отправить данные в АС Фрод-монитронг без предварительного сохранения +
ППРБ ЮЛ Digital B2B -> ППРБ ЮЛ История операций События антифрода -> DocumentWithoutSavingService -> analyzeOperation

===	Интеграции с платформенными сервисами

* Прикладной журнал — kafka, TLS. Тип событий для StandIn: ORM_CV

Аудит не используется, согласование от Огнева А. получено.

=== Особенности интеграции с прикладным журналом

Тип событий в прикладном журнале для StandIn — ORM_CV.