==	Параметры конфигурации

=== Стендозависимые параметры деплоя
Описание основных параметров: http://dev-sbbol2.sigma.sbrf.ru/docs/openshift-environments/master/

Описание переменных в openshift-environmets

.openshift.yml
[%collapsible]
====
[source,properties]
----
openshift:
  os_host: "dev-terra000006-idm.ocp.delta.sbrf.ru"
  io_control_panel: ci02281165-control-plane
  mesh_discovery_address: istiod-basic-install.ci02281165-control-plane.svc

os_project:
  host: "https://api.dev-terra000006-idm.ocp.delta.sbrf.ru:6443"
  project: ci02281165-antifraud
  pods: 1
  name: antifraud
  type: factory
  health_check: true
  istio:
    ingress:
      routes:
        - host: ingress-ci02281165-antifraud-tls.apps.dev-terra000006-idm.ocp.delta.sbrf.ru
          port: 5443
          containerPort: 8080
          name: mtls
          certificates:
            ca: "{{ secrets['istio-ingressgateway-ca-certs'].volume.mount }}"
            cert: "{{ secrets['istio-ingressgateway-certs'].volume.mount }}"
        - host: ingress-ci02281165-antifraud-geo-tls.apps.dev-terra000006-idm.ocp.delta.sbrf.ru
          port: 5441
          containerPort: 8080
          name: mtls-geo
          certificates:
            ca: "{{ secrets['istio-ingressgateway-ca-geo-certs'].volume.mount }}"
            cert: "{{ secrets['istio-ingressgateway-geo-certs'].volume.mount }}"
        - host: ingress-ci02281165-antifraud-ott.apps.dev-terra000006-idm.ocp.delta.sbrf.ru
          port: 5444
          containerPort: 8080
          name: ott
          certificates:
            ca: "{{ secrets['istio-ingressgateway-ca-certs'].volume.mount }}"
            cert: "{{ secrets['istio-ingressgateway-certs'].volume.mount }}"
        - host: ingress-ci02281165-antifraud-geo-ott.apps.dev-terra000006-idm.ocp.delta.sbrf.ru
          port: 5442
          containerPort: 8080
          name: ott-geo
          certificates:
            ca: "{{ secrets['istio-ingressgateway-ca-ott-geo-certs'].volume.mount }}"
            cert: "{{ secrets['istio-ingressgateway-ott-geo-certs'].volume.mount }}"
        - host: ingress-ci02281165-antifraud-geo-hc.apps.dev-terra000006-idm.ocp.delta.sbrf.ru
          port: 5446
          containerPort: 8080
          name: healthcheck
          certificates:
            ca: "{{ secrets['istio-ingressgateway-ca-hc-certs'].volume.mount }}"
            cert: "{{ secrets['istio-ingressgateway-hc-certs'].volume.mount }}"
      ott:
        key_store: dev-antifraud.p12
        trust_store: sigma_ott_trust.p12
        OTT_MODULE_ID: dev-antifraud
      pods: 1
      fluentbit: &fluentbit_resources
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
            ephemeral_storage: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
            ephemeral_storage: 256Mi
      proxy: &proxy_resources
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
            ephemeral_storage: 32Mi
          limits:
            cpu: 200m
            memory: 500Mi
            ephemeral_storage: 64Mi
    egress:
      pods: 1
      http:
        port: 8080
      mtls:
        port: 8443
      fluentbit: *fluentbit_resources
      proxy: *proxy_resources
      ott:
        port: 5443
        key_store: dev-antifraud.p12
        trust_store: sigma_ott_trust.p12
        OTT_MODULE_ID: dev-antifraud

nexus:
  base_uri: https://nexus-ci.delta.sbrf.ru/repository
  repository: maven-distr-release
  group: CI02473994
  artifactId: CI03045533

registry_area: docker-release.registry-ci.delta.sbrf.ru
versionMask: "D-\\d{2}\\.\\d{3}\\.\\d{2}_\\d{4}"

fluentbit:
  module_id: pprb4-digital-fraud

app_journal:
  secret: secret-appjournalstubsettings

context_prefix: /antifraud/

fraud:
  adapter:
    context: /asfm/v1.0/pprb_bhb_hist_b2b_aful/notify

standin:
  cloud:
    client:
      subscription_kafka_concurrency: 5
      kafka_retry: 3
      retry_timeout: 600000
  plugin:
    configuration:
      replication_strategy: STANDIN_LOCKS
      serializer_type: BINARY_KRYO
      partition_lock_mode: NONE
      partition_multiplying_mode: FORBIDDEN
      ordering_control_strategy: IDEMPOTENT_ORDERING_CONTROL
----
====

Пример конфигурации для обновления БД

.liquibase.yml
[%collapsible]
====
[source]
----
liquibase_download_uri: https://nexus.sigma.sbrf.ru/nexus/service/local/repositories/SBT_CI_distr_repo/content/SBBOL_UFS/liquibase/3.10.3-postgres/liquibase-3.10.3-postgres.tgz
# имя файла со скриптами БД, не менять
liquibase_changelog_file: changelog.yaml
# Может разойтись с точками интеграций и не может ссылаться на них из-за отсутствия params.yml в момент обновления базы
liquibase_databases:
  - name: "{{ db_main_name }}"
    schema: sbbol_antifraud
    default_schema: sbbol_antifraud
    user: "{{ db_main_user }}"
    password: "{{ db_main_password }}"
    driver_class: org.postgresql.Driver
    defaults_file: liquibase.properties
    connection_string: "jdbc:postgresql://{% for address in db_main_addresses %}{{ address.host }}:{{ address.port }}{% if not loop.last %},{% endif %}{% endfor %}/{{ db_main_name }}?prepareThreshold=0&currentSchema=sbbol_antifraud"
# Кастомные параметры, необходимые для проливки БД
custom_parameters:
  tablespace_t: pg_default
  tablespace_i: pg_default
  defaultSchemaName: sbbol_antifraud
----
====

.database.yml
[%collapsible]
====
[source]
----
# параметры подключения к MAIN БД
db_main_addresses:
  - host: 10.53.223.31
    port: 5433
db_main_name: sbbol_antifraud # имя БД
db_main_user: sbbol_antifraud # логин пользователя
db_main_password: !vault | # волтованный пароль пользователя БД
  $ANSIBLE_VAULT;1.1;AES256
  66373939303336363234383165313862646561313865373135616330623466653239343337633038
  3539373239353139313934623337643333363262633434310a356235633263633061356638633331
  61646137366566353034336531656430396137393330613338343238656337363936333364633661
  3433323533313864640a343538386332303539313939653337343838353465356637343965356636
  65346431303939643561313836633131616235656362643063303065666133353838

# параметры подключения к SI БД
db_si_addresses:
  - host: 10.53.223.31
    port: 5433
db_si_name: fake
db_si_user: fake
db_si_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66373939303336363234383165313862646561313865373135616330623466653239343337633038
  3539373239353139313934623337643333363262633434310a356235633263633061356638633331
  61646137366566353034336531656430396137393330613338343238656337363936333364633661
  3433323533313864640a343538386332303539313939653337343838353465356637343965356636
  65346431303939643561313836633131616235656362643063303065666133353838
----
====

.secman.yml
[%collapsible]
====
[source]
---
secman:
  sigma:
    jenkins:
      credentials:
        token:
          os:
            vaultUrl: "https://t.secrets.delta.sbrf.ru"
            vaultCredentialId: approle_dev_dcb-delta
            path: CI00149046_CI00363109/A/SBBOL/JEN/DEV/KV/ST_OpenShiftToken_ci02281165-antifraud
  openshift:
    enabled: true
    address: t.secrets.delta.sbrf.ru
    role: ci02281165-antifraud
    tenant: CI02281165_CI02352957
    inject_secrets:
      app:
        pgdb-si-secret:
          type: file
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/pgdb-si-secret
          volume:
            mount: /deployments/credentials/si_db
          secrets:
            secret.properties: secret.properties
        pgdb-main-secret:
          type: file
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/pgdb-main-secret
          volume:
            mount: /deployments/credentials/main_db
          secrets:
            secret.properties: secret.properties
        secret-appjournalstubsettings:
          type: file
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/secret-appjournalstubsettings
          volume:
            mount: /deployments/config/app_journal
          secrets:
            appJournal.properties: appJournal.properties
      ingress:
        istio-ingressgateway-ca-certs:
          type: file
          secrets:
            chain.pem: chain.pem
          volume:
            mount: /etc/istio/ingressgateway-ca-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-ca-certs
        istio-ingressgateway-certs:
          type: file
          secrets:
            tls.crt: tls.crt
            tls.key: tls.key
          volume:
            mount: /etc/istio/ingressgateway-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-certs
        istio-ingressgateway-ca-geo-certs:
          type: file
          secrets:
            chain.pem: chain.pem
          volume:
            mount: /etc/istio/istio-ingressgateway-ca-geo-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-ca-geo-certs
        istio-ingressgateway-geo-certs:
          type: file
          secrets:
            tls.crt: tls.crt
            tls.key: tls.key
          volume:
            mount: /etc/istio/istio-ingressgateway-geo-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-geo-certs
        istio-ingressgateway-ca-ott-geo-certs:
          type: file
          secrets:
            chain.pem: chain.pem
          volume:
            mount: /etc/istio/istio-ingressgateway-ca-ott-geo-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-ca-ott-geo-certs
        istio-ingressgateway-ott-geo-certs:
          type: file
          secrets:
            tls.crt: tls.crt
            tls.key: tls.key
          volume:
            mount: /etc/istio/istio-ingressgateway-ott-geo-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-ott-geo-certs
        istio-ingressgateway-ca-hc-certs:
          type: file
          secrets:
            chain.pem: chain.pem
          volume:
            mount: /etc/istio/istio-ingressgateway-ca-hc-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-ca-hc-certs
        istio-ingressgateway-hc-certs:
          type: file
          secrets:
            tls.crt: tls.crt
            tls.key: tls.key
          volume:
            mount: /etc/istio/istio-ingressgateway-hc-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-ingressgateway-hc-certs
      egress:
        istio-egressgateway-ca-certs:
          type: file
          secrets:
            chain.pem: chain.pem
          volume:
            mount: /etc/istio/egressgateway-ca-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-egressgateway-ca-certs
        istio-egressgateway-certs:
          type: file
          secrets:
            tls.crt: tls.crt
            tls.key: tls.key
          volume:
            mount: /etc/istio/egressgateway-certs
          path: CI02281165_CI02352957/A/SBBOL/OSH/DEV/KV/ci02281165-antifraud/istio-egressgateway-certs
----
====

=== Точки интеграции

Используются следующие точки интеграции:

* Прикладной журнал
* База данных фабрики Main
* База данных фабрики SI
* Системный журнал
* Сервера АС Рефлекс (ORM dynatrace)
* Взаимодействие через OTT
* Антифрод ФЛ.Интеграционный сервис(1099171)

.params.yml
[%collapsible]
====
[source]
----
integration_entries:
  - "{{ int.pprb.appjournal.v1_0 }}"
  - "{{ int.pprb.db_main.v1_0 }}"
  - "{{ int.pprb.db_si.v1_0 }}"
  - "{{ int.pprb.fluentbit.v1_0 }}"
  - "{{ int.dynatrace.latest.servers }}"
  - "{{ int.ott.v2_0 }}"
  - "{{ int.pprb.CI1099171_antifraud_integration_service.v1_0 }}"

int_entry:
  antifraud:
    fpis: "{{ int.pprb.CI1099171_antifraud_integration_service.v1_0 }}"
----
====

.integration.yml
[%collapsible]
====
[source]
----
int:
  pprb:
    appjournal:
      v1_0:
        - name: appjournal1
          host: 1sbtatlas.sigma.sbrf.ru
          ip: 10.128.11.11
          port: '9092'
          egress_port: '9991'
          ott: false
          mtls: false
          protocol: TCP
          url: dummy
          resolution: STATIC
        - name: appjournal6
          host: 6sbtatlas.sigma.sbrf.ru
          ip: 10.128.11.11
          port: '9092'
          egress_port: '9996'
          ott: false
          mtls: false
          protocol: TCP
          url: dummy
          resolution: STATIC
    db_main:
      v1_0:
        - name: db-main
          host: tkled-pprb00137.vm.esrt.cloud.sbrf.ru
          ip: 10.53.223.31
          port: '5433'
          egress_port: '1526'
          ott: false
          mtls: false
          protocol: TCP
          resolution: STATIC
    db_si:
      v1_0:
        - name: db-si
          host: tkled-pprb00137-fake.vm.esrt.cloud.sbrf.ru
          ip: 10.53.223.31
          port: '5433'
          egress_port: '1527'
          ott: false
          mtls: false
          protocol: TCP
          resolution: STATIC
    fluentbit:
      v1_0:
        - name: fluent-bit-ott
          host: sbtatlas.sigma.sbrf.ru
          port: '443'
          istio_mesh_port: '80'
          protocol: HTTP
          mtls: true
          ott: true
    CI1099171_antifraud_integration_service:
      v1_0:
        name: antifraud-integration-service
        host: fake-host.sigma.sbrf.ru
        port: '8443'
        ott: false
        mtls: true
        protocol: HTTP
        subjectAltNames: []
  dynatrace:
    latest:
      servers:
        - name: dynatrace
          resolution: STATIC
          url: http://10.53.90.60
          host: tkles-mvp000199.vm.esrt.cloud.sbrf.ru
          ip: 10.53.90.60
          port: 9999
          egress_port: 9990
          istio_mesh_port: 9990
          protocol: TCP
          ott: false
          mtls: false
  ott:
    v2_0:
      - name: ott-1
        protocol: TCP
        resolution: STATIC
        ott: false
        mtls: false
        host: se-sbbol.dev.draft.ott1
        ip: 10.53.99.178
        port: 8443
        via_egress: false
      - name: ott-2
        protocol: TCP
        resolution: STATIC
        ott: false
        mtls: false
        host: se-sbbol.dev.draft.ott2
        ip: 10.53.96.30
        port: 8443
        via_egress: false
----
====

=== Секреты OSE

Стандартные для фабрик секреты

==== Сертификаты для Istio

.secrets.yml
[%collapsible]
====
[source,properties]
----
  istio-ingressgateway-ca-certs:
    source: file
    files:
      chain.pem: files/test-ca-chain.pem
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/ingressgateway-ca-certs
  istio-ingressgateway-certs:
    source: encrypted-file
    files:
      tls.crt: files/antifraud.pem
      tls.key: files/antifraud.key
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/ingressgateway-certs
  istio-ingressgateway-ca-geo-certs:
    source: file
    files:
      chain.pem: files/test-ca-chain.pem
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-ca-geo-certs
  istio-ingressgateway-geo-certs:
    source: encrypted-file
    files:
      tls.crt: files/wildcard-apps-dev-gen.pem
      tls.key: files/wildcard-apps-dev-gen.key
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-geo-certs
  istio-ingressgateway-ca-ott-geo-certs:
    source: file
    files:
      chain.pem: files/test-ca-chain.pem
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-ca-ott-geo-certs
  istio-ingressgateway-ott-geo-certs:
    source: encrypted-file
    files:
      tls.crt: files/wildcard-apps-dev-gen.pem
      tls.key: files/wildcard-apps-dev-gen.key
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-ott-geo-certs
  istio-ingressgateway-ca-hc-certs:
    source: file
    files:
      chain.pem: files/test-ca-chain.pem
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-ca-hc-certs
  istio-ingressgateway-hc-certs:
    source: encrypted-file
    files:
      tls.crt: files/antifraud.pem
      tls.key: files/antifraud.key
    deployment: ingress-gateway
    volume:
      mount: /etc/istio/istio-ingressgateway-hc-certs
  istio-egressgateway-ca-certs:
    source: file
    files:
      chain.pem: files/test-ca-chain.pem
    deployment: istio-egressgateway
  istio-egressgateway-certs:
    source: encrypted-file
    files:
      tls.crt: files/antifraud.pem
      tls.key: files/antifraud.pem
    deployment: istio-egressgateway
----
====

==== Секреты БД

.secrets.yml
[%collapsible]
====
[source,properties]
----
secrets:
  pgdb-si-secret:
    source: template
    files:
      secret.properties: templates/sbbol_pprb_draft/secret-db-si.j2
    deployment: app
  pgdb-main-secret:
    source: template
    files:
      secret.properties: templates/sbbol_pprb_draft/secret-db-main.j2
    deployment: app
----
====

.pgdb-main-secret (ключ secret.properties)
[%collapsible]
====
[source,properties]
----
spring.datasource.username=schema
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://0.0.0.0:1526/schema
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
----
====

.pgdb-si-secret (ключ secret.properties)
[%collapsible]
====
[source,properties]
----
standin.datasource.username=schema
standin.datasource.password=password
standin.datasource.url=jdbc:postgresql://1.1.1.1:1526/schema
standin.datasource.driver-class-name=org.postgresql.Driver
standin.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
----
====

==== Секреты для OTT

.secrets.yml
[%collapsible]
====
[source,properties]
----
secrets:
  ott-secrets:
    source: file
    files:
      sigma_ott_trust.p12: files/ott/sigma_ott_trust.p12
      dev-antifraud.p12: files/ott/dev-antifraud.p12
    deployment: app
  ott-passwords:
    source: property
    properties:
      OTT_CERTSTORE_PRIVATE_KEY_PWD: "{{ OTT_CERTSTORE_PRIVATE_KEY_PWD }}"
      OTT_CERTSTORE_PWD: "{{ OTT_CERTSTORE_PWD }}"
      OTT_TRUST_STORE_PWD: "{{ OTT_TRUST_STORE_PWD }}"
    deployment: app
----
====

=== Параметры настройки БД

Настройка БД — типовая.

https://confluence.sberbank.ru/pages/viewpage.action?pageId=3313801156
