==	Деплой

Приложение разворачивается в OpenShift с использованием платформенной джобы `Install_EIP`.
Переданная сборка представляет собой архив с yml-файлами, в которые подставляются значения из конфигурации `Install_EIP`
при запуске джобы деплоя, после чего каждый из ресурсов применяется в OpenShift (`oc apply -f <filename>`).

По результатам работы джобы в OpenShift создается 3 основных `Deployment`: `Ingress`, `Egress` и deployment с приложением.

К namespace должен быть подключен istio, так как проект использует конфигурации istio для управления трафиком внутри namespace.

В namespace создается 5 точек входа (`Route`):

* tls-роут, закрытый через SAN - используется только для HealthCheck, потребители отсутствуют
* tls-роут через геобалансировщик, закрытый через SAN - используется только для HealthCheck, потребители отсутствуют
* ott-роут, выполняющий валидацию токена OTT
* ott-роут через геобалансировщик, выполняющий валидацию токена OTT
* открытый health-check роут, по которому доступ разрешен только к контексту `/actuator/...`

Для проверки корректной установки можно выполнить следующие запросы:

* Вызов HealthCheck +

[source,bash]
----
curl -v https://ingress-ci03045533-sbbol-antifraud-tls.apps.dev-gen2.sigma.sbrf.ru/antifraud/actuator/health -H "Content-Type: application/json" --cacert chain.pem --cert cert.pem --key cert.key
----

Пример ответа:
[source,json]
----
{"status":"UP","components":{"dataSpaceCoreIndicator":{"status":"UP","details":{"DataSpaceCore":"Available"}},"diskSpace":{"status":"UP","details":{"total":107321753600,"free":78606151680,"threshold":10485760,"exists":true}},"livenessState":{"status":"UP"},"ping":{"status":"UP"},"readinessState":{"status":"UP"}},"groups":["liveness","readiness"]}
----

* Создание или обновление события в агрегаторе антифрод (*вставляет и или обновляет данные в базе!*) +

.payment_saveorupdate.json
[%collapsible]
====
[source,json]
----
{
  "jsonrpc": "2.0",
  "method": "saveOrUpdateData",
  "id": 1,
  "params": {
    "dataparams": {
      "dboOperation": "PAYMENT_DT_0401060",
      "timeStamp": "2020-03-23T12:34:33",
      "orgGuid": "00000000-0000-0000-0000-000000000000",
      "digitalId": "1111",
      "timeOfOccurrence": "2020-03-23T15:10:05",
      "document": {
        "id": "00000000-0000-0000-0000-000000000000",
        "number": 257,
        "date": "2020-03-23",
        "amount": 332484,
        "currency": "RUB",
        "executionSpeed": "FEW_HOURS",
        "otherAccBankType": "OTHER_BANK",
        "otherAccOwnershipType": "ME_TO_YOU",
        "transferMediumType": "WIRE",
        "destination": "Возврат денежных средств по заказу 123412-93",
        "payer": {
          "accountNumber": "40702810500112958634",
          "inn": "7704681547"
        },
        "receiver": {
          "balAccNumber": "45678667897655789978",
          "otherAccName": "ООО Рога и копыта",
          "otherBicCode": "040012002",
          "otherAccType": "BILLER",
          "inn": "5038956712"
        }
      },
      "signs": [
        "{\"httpAccept\": \"text/javascript, text/html, application/xml, text/xml, */*\", \"httpReferer\": \"http://localhost:8000/reference_application/Login.do\", \"httpAcceptChars\": \"ISO-8859-1,utf-8;q=0.7,*;q=0.7\", \"httpAcceptEncoding\": \"gzip, deflate\", \"httpAcceptLanguage\": \"en,en-us;q=0.5\", \"ipAddress\": \"78.245.9.87\", \"privateIpAddress\": \"172.16.0.0\", \"tbCode\": \"546738\", \"userAgent\": \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.1; .NET CLR 2.0.50727)\", \"devicePrint\": \"version%3D3%2E4%2E1%2E0%5F1%26pm%5Ffpua%3Dmozilla%2F4%2E0%20%28compatible%3B%20\", \"channelIndicator\": \"WEB\", \"userGuid\": \"7c7bd0c1-2504-468e-8410-b4d00522014f\", \"signTime\": \"2020-03-23T15:01:15\", \"signLogin\": \"novikova01\", \"signCryptoprofile\": \"Новикова Ольга Трофимовна\", \"signCryptoprofileType\": \"OneTimePassword\", \"signToken\": \"signToken\", \"signType\": \"Единственная подпись\", \"signImsi\": \"6176CB3B83F33108E0CBD9F411CAF608\", \"signCertId\": \"signCertId\", \"signPhone\": \"915 168-67-32\", \"signEmail\": \"no@glavbaza36.ru\", \"signSource\": \"SMS\", \"clientDefinedChannelIndicator\": \"PPRB_BROWSER\"}",
        "{\"httpAccept\": \"text/javascript, text/html, application/xml, text/xml, */*\", \"httpReferer\": \"http://localhost:8000/reference_application/Login.do\", \"httpAcceptChars\": \"ISO-8859-1,utf-8;q=0.7,*;q=0.7\", \"httpAcceptEncoding\": \"gzip, deflate\", \"httpAcceptLanguage\": \"en,en-us;q=0.5\", \"ipAddress\": \"91.225.10.97\", \"privateIpAddress\": \"192.11.0.0\", \"tbCode\": \"546738\", \"userAgent\": \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.1; .NET CLR 2.0.50727)\", \"mobSdkData\": \"version%20nt%206%2E1%3B%20win64%3B%20x64%3B%20trident%2F4%2E0%3B%20%2Enet\", \"channelIndicator\": \"WEB\", \"userGuid\": \"7c7bd0c1-2504-468e-8410-b4d00522014f\", \"signTime\": \"2020-03-23T15:28:25\", \"signLogin\": \"ivanov05\", \"signCryptoprofile\": \"Иванов Иван Иванович\", \"signCryptoprofileType\": \"OneTimePassword\", \"signToken\": \"signToken\", \"signType\": \"Единственная подпись\", \"signImsi\": \"6176CB3B83F33108E0CBD9F411CAF608\", \"signCertId\": \"signCertId\", \"signPhone\": \"903 158-55-12\", \"signEmail\": \"iv@glavbaza36.ru\", \"signSource\": \"SMS\", \"clientDefinedChannelIndicator\": \"PPRB_BROWSER\"}",
        "{\"httpAccept\": \"text/javascript, text/html, application/xml, text/xml, */*\", \"httpReferer\": \"http://localhost:8000/reference_application/Login.do\", \"httpAcceptChars\": \"ISO-8859-1,utf-8;q=0.7,*;q=0.7\", \"httpAcceptEncoding\": \"gzip, deflate\", \"httpAcceptLanguage\": \"en,en-us;q=0.5\", \"ipAddress\": \"75.241.3.77\", \"privateIpAddress\": \"168.12.0.0\", \"tbCode\": \"546738\", \"userAgent\": \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.1; .NET CLR 2.0.50727)\", \"devicePrint\": \"version%3D3%2E4%2E1%2E0%5F1%26pm%5Ffpua%3Dmozilla%2F4%2E0%20%28compatible%3B%20\", \"channelIndicator\": \"WEB\", \"userGuid\": \"7c7bd0c1-2504-468e-8410-b4d00522014f\", \"signTime\": \"2020-03-23T16:00:05\", \"signLogin\": \"petrov11\", \"signCryptoprofile\": \"Петров Петр Петрович\", \"signCryptoprofileType\": \"OneTimePassword\", \"signToken\": \"signToken\", \"signType\": \"Единственная подпись\", \"signImsi\": \"6176CB3B83F33108E0CBD9F411CAF608\", \"signCertId\": \"signCertId\", \"signPhone\": \"916 243-67-34\", \"signEmail\": \"pe@glavbaza36.ru\", \"signSource\": \"SMS\", \"clientDefinedChannelIndicator\": \"PPRB_BROWSER\"}"
      ]
    }
  }
}
----
====

[source,bash]
----
curl -v https://ingress-ci03045533-sbbol-antifraud-tls.apps.dev-gen2.sigma.sbrf.ru/antifraud/v1/savedata -d "@payment_saveorupdate.json" -H "Content-Type: application/json" -X POST --cacert chain.pem --cert cert.pem --key cert.key
----

Пример ответа:
[source,json]
----
{"jsonrpc":"2.0","id":1,"result":{"requestId":"ba5c098e-ca36-41c5-958e-6e1f6223beb3"}}
----

* Вызов ФП ИС для анализа события +

.paymentfeed_analyze.json
[%collapsible]
====
[source,json]
----
{
  "jsonrpc": "2.0",
  "method": "analyzeOperation",
  "id": 1,
  "params": {
    "analyzeparams": {
      "dboOperation": "PAYMENT_DT_0401060",
      "docId": "00000000-0000-0000-0000-000000000000"
    }
  }
}
----
====

[source,bash]
----
curl -v https://ingress-ci03045533-sbbol-antifraud-tls.apps.dev-gen2.sigma.sbrf.ru/antifraud/v1/analyzeoperation -d "@paymentfeed_analyze.json" -H "Content-Type: application/json" -X POST --cacert chain.pem --cert cert.pem --key cert.key
----

Пример ответа:
[source,json]
----
{"jsonrpc":"2.0","id":1,"result":{"transactionId":"c9ec0107588b433ea025fcf31443e88c","actionCode":"ALLOW"}}
----
