-- liquibase formatted sql

--changeset pisarev-fm:t_document_drop_customer_columns
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERSURNAME;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERNAME;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERPATRONYMIC;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERBIRTHDAY;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERPASSPORTNUMBER;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERPASSPORTSERIES;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERMOBILEPHONE;
ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERSTATUS;

--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERSURNAME VARCHAR(100);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERSURNAME IS 'Фамилия клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERNAME VARCHAR(100);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERNAME IS 'Имя клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERPATRONYMIC VARCHAR(100);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERPATRONYMIC IS 'Отчество клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERBIRTHDAY DATE;
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERBIRTHDAY IS 'Дата рождения клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERPASSPORTNUMBER VARCHAR(30);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERPASSPORTNUMBER IS 'Номер паспорта клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERPASSPORTSERIES VARCHAR(30);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERPASSPORTSERIES IS 'Серия паспорта клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERMOBILEPHONE VARCHAR(50);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERMOBILEPHONE IS 'Номер мобильного телефона клиента';
--rollback ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERSTATUS VARCHAR(30);
--rollback COMMENT ON COLUMN T_DOCUMENT.CUSTOMERSTATUS IS 'Статус клиента';

--changeset pisarev-fm:t_document_add_customerdatalist
ALTER TABLE T_DOCUMENT ADD COLUMN CUSTOMERSDATALIST JSON;
COMMENT ON COLUMN T_DOCUMENT.CUSTOMERSDATALIST IS 'Данные клиентов';
--rollback ALTER TABLE T_DOCUMENT DROP COLUMN CUSTOMERSDATALIST;
