LiquibaseRoll:
  mainDb:
    dbUrl: jdbc:postgresql://33315-tcp.np.dev-gen2.sigma.sbrf.ru:33315/dataspace
    dbUser: dataspace
    dbPassword: dataspace
    tableSpaceT: pg_default
    dbDriver: org.postgresql.Driver
Installer:
  openShiftUrl: api.dev-gen2.sigma.sbrf.ru:6443
  openShiftProject: ci02642164-edevgen2-pprb-kib-dev-sbbol-antifraud
  ingressGatewayName: ingressgateway-ci02642164-edevgen2-pprb-kib-dev-sbbol-antifraud
  setUniqModuleName: false
  parameters:
    dataspace-core-template:
      MODULE_NAME: dataspace-core-sbbol-antifraud
      mainDataBaseSecretId: dataspace-core-pgdb-custom-secret
      standinDataBaseSecretId: dataspace-core-pgdb-custom-secret
      standinEnabled: false
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      requestCPU: 500m
      requestMemory: 2Gi
    dataspace-gigabas-template:
      MODULE_NAME: dataspace-gigabas-sbbol-antifraud
      mainDataBaseSecretId: dataspace-core-pgdb-custom-secret
      standinDataBaseSecretId: dataspace-core-pgdb-custom-secret
      MODEL_PACKAGE_NAME: TODODELETE
      requestCPU: 500m
      requestMemory: 1024Mi
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
    event-feed-template:
      MODULE_NAME: sbbol-antifraud
      RUN_DEBUG: false
      dataSpaceCoreUrl: "http://svc-dataspace-core-sbbol-antifraud:8080"
      requestCPU: 500m
      requestMemory: 1024Mi
      FLUENTBIT_IMAGE: registry.sigma.sbrf.ru/pprb/ci00641491/ci02469991_logger/fluent-bit:1.4.5
      needInstallOutRoute: true
