Deployer:
  releasers: "16693193,18396199,cab-sa-dcbmsc05"
  needBuildImage: "true"
  needChangeImageUrl: "true"

commons:
  ci:
    credentials: DS_MSC5
  openshift:
    credentials: DS_MSC5
    url: api.dev-gen2.sigma.sbrf.ru:6443
  nexus:
    credentials: DS_MSC5
    url: sbtatlas.sigma.sbrf.ru/nexus
    snapshotRepository: corp-snapshots
    releaseRepository: corp-releases
  registry:
    credentials: DS_MSC5
    url: registry.sigma.sbrf.ru
    snapshotProject: pprb-dev/ci02473994/ci03045533_sbbol_antifraud_dev
    releaseProject: pprb/ci02473994/ci03045533_sbbol_antifraud
  git:
    credentials: dataspace-bot-ssh
  sonar:
    url: https://sbt-sonarqube.sigma.sbrf.ru/
    token: 2b8e7f129e433c0edd46a6212fa3a5f13f551ab8
    projectKey: ru.sberbank.pprb.sbbol.antifraud
  maven:
    pathSettings: ./config/sigma/settings.xml

QualityGates:
  sbrf:
    url: https://sbrf-nexus.sigma.sbrf.ru/nexus
    groupId: Nexus_PROD.CI03045533_sbbol-antifraud
    credentials: DS_MSC5
    repositoryId: release
  sast:
    credentials: DS_SAST_CRED
    configPath: config/devsecops-config.yml
  mode: scanAndFlags