kind: Service
apiVersion: v1
metadata:
  name: svc-antifraud
  annotations:
    description: "Service for antifraud"
    # Аннотация для включения сбора метрик
    prometheus.io.scrape: "true"
    # Аннотация для указания HTTP endpoint с метриками приложения
    prometheus.io.path: "/actuator/prometheus"
    # Аннотация для указания порта подключения к HTTP endpoint с метриками
    prometheus.io.port: "8080"
spec:
  selector:
    app: antifraud
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: tcp-debug
      port: 8000
      targetPort: 8000
  type: ClusterIP