--liquibase formatted sql

--changeset pisarev-fm:sys_lastchangedate_paymentoperation
ALTER TABLE T_PAYMENTOPERATION ADD COLUMN SYS_LASTCHANGEDATE TIMESTAMP;
CREATE INDEX I_PAYMENTOPERATION_LASTCHANGEDATE ON T_PAYMENTOPERATION(SYS_LASTCHANGEDATE);
COMMENT ON COLUMN T_PAYMENTOPERATION.SYS_LASTCHANGEDATE IS 'Системное поле с датой и временем последнего изменения сущности, используется для сверки БД в двух контурах с помощью ПЖ';
--rollback ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;

--changeset pisarev-fm:sys_lastchangedate_sbppaymentoperation
ALTER TABLE T_SBPPAYMENTOPERATION ADD COLUMN SYS_LASTCHANGEDATE TIMESTAMP;
CREATE INDEX I_SBPPAYMENTOPERATION_SYS_LASTCHANGEDATE ON T_SBPPAYMENTOPERATION(SYS_LASTCHANGEDATE);
COMMENT ON COLUMN T_SBPPAYMENTOPERATION.SYS_LASTCHANGEDATE IS 'Системное поле с датой и временем последнего изменения сущности, используется для сверки БД в двух контурах с помощью ПЖ';
--rollback ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;

--changeset pisarev-fm:sys_lastchangedate_electronicreceiptoperation
ALTER TABLE T_ELECTRONICRECEIPTOPERATION ADD COLUMN SYS_LASTCHANGEDATE TIMESTAMP;
CREATE INDEX I_ELECTRONICRECEIPTOPERATION_SYS_LASTCHANGEDATE ON T_ELECTRONICRECEIPTOPERATION(SYS_LASTCHANGEDATE);
COMMENT ON COLUMN T_ELECTRONICRECEIPTOPERATION.SYS_LASTCHANGEDATE IS 'Системное поле с датой и временем последнего изменения сущности, используется для сверки БД в двух контурах с помощью ПЖ';
--rollback ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;
