--liquibase formatted sql

--changeset pisarev-fm:rename_t_paymentoperation_column_timestamp_
ALTER TABLE T_PAYMENTOPERATION RENAME COLUMN TIMESTAMP_ TO EVENTTIME;
--rollback ALTER TABLE T_PAYMENTOPERATION RENAME COLUMN EVENTTIME TO TIMESTAMP_;

--changeset pisarev-fm:rename_t_sbppaymentoperation_column_timestamp_
ALTER TABLE T_SBPPAYMENTOPERATION RENAME COLUMN TIMESTAMP_ TO EVENTTIME;
--rollback ALTER TABLE T_SBPPAYMENTOPERATION RENAME COLUMN EVENTTIME TO TIMESTAMP_;

--changeset pisarev-fm:rename_t_electronicreceiptoperation_column_timestamp_
ALTER TABLE T_ELECTRONICRECEIPTOPERATION RENAME COLUMN TIMESTAMP_ TO EVENTTIME;
--rollback ALTER TABLE T_ELECTRONICRECEIPTOPERATION RENAME COLUMN EVENTTIME TO TIMESTAMP_;