--liquibase formatted sql

--changeset pisarev-fm:drop_dataspace_tables
DROP TABLE LC_REPL_CR_CRBATCH_IDENTIFIERS,
    T_ELECTRONICRECEIPTOPERATIONAPICALL,
    T_PAYMENTOPERATIONAPICALL,
    T_REPL_AGGLOCK_CRLOCK,
    T_REPL_AGGLOCK_ELECTRONICRECEIPTOPERATION,
    T_REPL_AGGLOCK_PAYMENTOPERATION,
    T_REPL_AGGLOCK_ROOTDICTIONARY,
    T_REPL_AGGLOCK_SBPPAYMENTOPERATION,
    T_REPL_AGGLOCKEVENT,
    T_REPL_CR_CRAGGREGATETASK,
    T_REPL_CR_CRBATCH,
    T_REPL_CR_CREPKEVENT,
    T_REPL_CR_CREPKEVENTBUFFER,
    T_REPL_CR_CRLOCK,
    T_REPL_CR_CRPROCESS,
    T_REPL_CR_CRREQUESTEVENT,
    T_REPL_CR_CRREQUESTEVENT_DUP_BY_AGGREGATE,
    T_REPL_CR_CRTASK,
    T_REPL_CR_INIT_SUBTASK,
    T_REPL_CR_INIT_TASK,
    T_ROOTDICTIONARY,
    T_SBPPAYMENTOPERATIONAPICALL;

--changeset pisarev-fm:t_paymentoperation_drop_dataspace_columns_from
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN TYPE;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_ISDELETED;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_PARTITIONID;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_OWNERID;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN SYS_RECMODELVERSION;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN CHGCNT;
ALTER TABLE T_PAYMENTOPERATION DROP COLUMN OFFFLAG;

--changeset pisarev-fm:t_sbppaymentoperation_drop_dataspace_columns_from
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN TYPE;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_ISDELETED;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_PARTITIONID;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_OWNERID;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN SYS_RECMODELVERSION;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN CHGCNT;
ALTER TABLE T_SBPPAYMENTOPERATION DROP COLUMN OFFFLAG;

--changeset pisarev-fm:t_electronicreceiptoperation_drop_dataspace_columns_from
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN TYPE;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_LASTCHANGEDATE;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_ISDELETED;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_PARTITIONID;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_OWNERID;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYS_RECMODELVERSION;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN CHGCNT;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN OFFFLAG;
ALTER TABLE T_ELECTRONICRECEIPTOPERATION DROP COLUMN SYSLASTHISTVERSION;