--liquibase formatted sql

--changeset pisarev-fm:change_type_electronicreceipt_docnumber
ALTER TABLE T_ELECTRONICRECEIPTOPERATION ALTER COLUMN DOCNUMBER TYPE VARCHAR(10);
--rollback ALTER TABLE T_ELECTRONICRECEIPTOPERATION ALTER COLUMN DOCNUMBER TYPE INTEGER USING DOCNUMBER::INTEGER;
