==	Интеграции

=== Интеграции с внешними АС-потребителями

Все вызовы фабрики потребителями выполняются по mTLS + OTT с проверкой по ACL.

Фабрика события антфирода обращается в ФП ИС по mTLS с проверкой SAN на стороне ФП ИС.

=== ACL (Access Lists)

Да, все API должны быть закрыты через ACL

1. Api для сохранения и обновления события в агрегаторе антифрод. +
Потребители: фабрика черновиков РПП +
ППРБ ЮЛ История операций B2B -> ППРБ ЮЛ История операций События антифрода -> AntiFraudDataService -> saveOrUpdateData
2. API для отправки события на анализ в АС Фрод Мониторинг через ФП ИС +
Потребители: фабрика исполнения РПП, фабрика СБП +
ППРБ ЮЛ История операций B2B -> ППРБ ЮЛ История операций События антифрода -> AntiFraudAnalyzeService -> analyzeOperation

===	Интеграции с платформенными сервисами

* Прикладной журнал — kafka, TLS. Тип событий для StandIn: Dataspace
* Мониторинг Рефлекс — интеграция на уровне агентов в неймспейсе

Аудит не используется, согласование от Огнева А. получено.
